### ISSUE TITLE
这，，，代码

### ISSUE THREAD

**Issue by mosentest** [dongjunkun/DropDownMenu#60]
Process: com.yyy.djk.dropdownmenu, PID: 13831
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yyy.djk.dropdownmenu/com.yyy.djk.dropdownmenu.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.yyydjk.library.DropDownMenu.setDropDownMenu(java.util.List, java.util.List, android.view.View)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2855)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2916)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6380)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.yyydjk.library.DropDownMenu.setDropDownMenu(java.util.List, java.util.List, android.view.View)' on a null object reference
        at com.yyy.djk.dropdownmenu.MainActivity.initView(MainActivity.java:132)
        at com.yyy.djk.dropdownmenu.MainActivity.onCreate(MainActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:6765)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2808)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2916) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6380) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

**Comment by mosentest** [comment]
implementation 'com.jakewharton:butterknife:8.0.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.0.1'
换了这，改了代码，没问题了
